"""empty message

Revision ID: 11aeee50cc6c
Revises: 2786d62e7bf3
Create Date: 2024-08-19 22:59:27.715270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11aeee50cc6c'
down_revision = '2786d62e7bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
