"""empty message

Revision ID: 1a939bf33f4d
Revises: 
Create Date: 2024-07-16 10:39:25.370952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1a939bf33f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_item_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_item_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=200), nullable=False),
    sa.Column('link', sa.VARCHAR(length=200), nullable=False),
    sa.Column('url', sa.VARCHAR(length=600), nullable=False),
    sa.Column('image_metadata', sqlite.JSON(), nullable=True),
    sa.Column('auction_item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['auction_item_id'], ['auction_items.id'], name='fk_auction_item_images_auction_item_id_auction_items'),
    sa.PrimaryKeyConstraint('id', name='pk_auction_item_images')
    )
    # ### end Alembic commands ###
