"""empty message

Revision ID: 41e690b93cbd
Revises: d71100cb6b5b
Create Date: 2024-08-20 16:14:59.917467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e690b93cbd'
down_revision = 'd71100cb6b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_goal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_performance_goal_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_performance_goal_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_goal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_performance_goal_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_performance_goal_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
