"""empty message

Revision ID: b5280eb033ca
Revises: 3a33bf2a79a4
Create Date: 2024-08-12 01:28:52.496422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5280eb033ca'
down_revision = '3a33bf2a79a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
