"""empty message

Revision ID: b950c679eb0f
Revises: 11aeee50cc6c
Create Date: 2024-08-20 15:03:14.606455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b950c679eb0f'
down_revision = '11aeee50cc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_sale_id_sale', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_feedback_sale_id_sale'), 'sale', ['sale_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feedback_sale_id_sale'), type_='foreignkey')
        batch_op.create_foreign_key('fk_feedback_sale_id_sale', 'sale', ['sale_id'], ['id'])

    # ### end Alembic commands ###
