"""empty message

Revision ID: d0c58931cc6d
Revises: 6a339c5cbdef
Create Date: 2024-08-18 13:36:23.748063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c58931cc6d'
down_revision = '6a339c5cbdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sale_branch_id_branch'), 'branch', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_branch_id_branch'), type_='foreignkey')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
