"""empty message

Revision ID: d7c1481808bf
Revises: 41e690b93cbd
Create Date: 2024-08-20 16:16:22.067999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c1481808bf'
down_revision = '41e690b93cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentive', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incentive_performance_goal_id_performance_goal', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_incentive_performance_goal_id_performance_goal'), 'performance_goal', ['performance_goal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentive', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_incentive_performance_goal_id_performance_goal'), type_='foreignkey')
        batch_op.create_foreign_key('fk_incentive_performance_goal_id_performance_goal', 'performance_goal', ['performance_goal_id'], ['id'])

    # ### end Alembic commands ###
